"""
Seed list of canonical AI/AI-infra startup names for entity resolution
(Phase IV). This mocks the "small database of 50 known AI startups" called
for in the brief. Each entry includes common real-world name variants we've
actually seen in the wild (filings, press mentions, casual references) so
the resolver has realistic ground truth to match against.
"""

CANONICAL_STARTUPS: dict[str, list[str]] = {
    "OpenAI": ["OpenAI, Inc.", "Open AI", "OpenAI Inc", "Open-AI", "openai.com"],
    "Anthropic": ["Anthropic PBC", "Anthropic, Inc.", "Anthropic AI"],
    "Google DeepMind": ["DeepMind", "Google Deep Mind", "DeepMind Technologies"],
    "Mistral AI": ["Mistral", "MistralAI", "Mistral A.I."],
    "Cohere": ["Cohere Inc.", "Cohere AI", "Cohere Technologies"],
    "Perplexity AI": ["Perplexity", "Perplexity.ai", "Perplexity Inc"],
    "Together AI": ["Together", "Together Computer", "TogetherAI"],
    "Hugging Face": ["HuggingFace", "Hugging Face Inc", "HF"],
    "Stability AI": ["StabilityAI", "Stability", "Stability.ai"],
    "Runway": ["RunwayML", "Runway AI", "Runway Machine Learning"],
    "Scale AI": ["Scale", "ScaleAI", "Scale.ai"],
    "Character.AI": ["Character AI", "CharacterAI", "Character Technologies"],
    "Inflection AI": ["Inflection", "InflectionAI"],
    "Adept AI": ["Adept", "Adept.ai", "Adept AI Labs"],
    "Imbue": ["Imbue AI", "Generally Intelligent"],
    "Cursor (Anysphere)": ["Anysphere", "Cursor", "Anysphere Inc"],
    "xAI": ["X.AI", "xAI Corp", "X AI"],
    "Groq": ["Groq Inc", "Groq, Inc."],
    "Cerebras Systems": ["Cerebras", "Cerebras Systems Inc"],
    "SambaNova Systems": ["SambaNova", "Sambanova Systems Inc"],
    "Lambda Labs": ["Lambda", "Lambda, Inc."],
    "CoreWeave": ["Core Weave", "CoreWeave Inc"],
    "Weights & Biases": ["Weights and Biases", "WandB", "W&B"],
    "LangChain": ["Lang Chain", "LangChain Inc"],
    "Pinecone": ["Pinecone Systems", "Pinecone.io"],
    "Weaviate": ["Weaviate B.V.", "Weaviate Inc"],
    "Qdrant": ["Qdrant Solutions", "Qdrant GmbH"],
    "Glean": ["Glean Technologies", "Glean.com", "Glean Work"],
    "Sierra": ["Sierra AI", "Sierra Platform"],
    "Harvey": ["Harvey AI", "Harvey Legal AI"],
    "Cognition Labs": ["Cognition", "Cognition AI", "Devin (Cognition)"],
    "Magic AI": ["Magic.dev", "Magic Labs"],
    "Suno": ["Suno AI", "Suno Inc"],
    "ElevenLabs": ["Eleven Labs", "ElevenLabs Inc"],
    "Synthesia": ["Synthesia AI", "Synthesia Ltd"],
    "Luma AI": ["Luma Labs", "Luma"],
    "Pika Labs": ["Pika", "Pika.art"],
    "World Labs": ["World Labs Inc", "WorldLabs"],
    "Sakana AI": ["Sakana", "Sakana AI Inc"],
    "01.AI": ["01 AI", "Yi (01.AI)", "Zero One AI"],
    "Moonshot AI": ["Moonshot", "Moonshot AI Inc", "Kimi (Moonshot AI)"],
    "Zhipu AI": ["Zhipu", "ChatGLM (Zhipu)", "Z.ai"],
    "DeepSeek": ["Deepseek AI", "Deep Seek", "DeepSeek-AI"],
    "AI21 Labs": ["AI21", "AI 21 Labs"],
    "Contextual AI": ["Contextual.ai", "Contextual"],
    "Reka AI": ["Reka", "Reka.ai"],
    "Codeium (Windsurf)": ["Codeium", "Windsurf", "Exafunction"],
    "Replit": ["Replit Inc", "Repl.it"],
    "Vercel": ["Vercel Inc", "ZEIT (Vercel)"],
    "Fireworks AI": ["Fireworks", "Fireworks.ai"],
    "Baseten": ["Baseten Labs", "Baseten Inc"],
}
